### ISSUE TITLE
Install is not idempotent

### ISSUE THREAD

**Issue by Stromweld** [newrelic/chef-install#13]
During a chef client run every subsequent run keeps running the execute resources for the install due to no idempotency check.

**Comment by NRhzhao** [comment]
This cookbook executes guided installation and doesn't have information on the version of the agent that gets installed.
ideally, the agent should be programmed to check for the latest version and skip installation if it's already up-to-date.

**Comment by Stromweld** [comment]
Best practice cookbook writing that would be done in the resource or recipe doing the install.

**Comment by kidk** [comment]
Hi @Stromweld 

Thanks for reaching out and creating this ticket. As mentioned by @NRhzhao this is a current limitation of the recipe, but we're always looking to improve. 

Could you give us your thoughts on why this is a concern? Is the duration of the recipe run the main problem?

Thanks a lot
